pipeline {
    agent any
    
    environment {
        REPO_FOLDER = 'home-ansible-servers'
        ANSIBLE_IMAGE = 'alpine/ansible:latest'
    }
    
    stages {
        stage('Cleanup Workspace') {
            steps {
                script {
                    // Remove existing folder if it exists
                    sh 'rm -rf $REPO_FOLDER'
                }
            }
        }

        stage('Checkout Repository') {
            steps {
                script {
                    // Clone the public repository
                    sh 'git clone https://github.com/fabricesemti80/home-ansible-servers.git $REPO_FOLDER'
                }
            }
        }
        
        stage('List Files') {
            steps {
                script {
                    // List contents of the checked-out repository
                    sh 'ls -la $REPO_FOLDER'
                }
            }
        }
        
        stage('Install Ansible Requirements in Container') {
            steps {
                script {
                    // Pull the latest Ansible image
                    sh "docker pull ${ANSIBLE_IMAGE}"
                    
                    // Install Ansible requirements inside the container
                    sh "docker run --rm -v \${PWD}/$REPO_FOLDER:/ansible ${ANSIBLE_IMAGE} ansible-galaxy install -r /ansible/requirements.yml"
                }
            }
        }
        
        stage('Run Ansible Playbook in Container') {
            steps {
                script {
                    // Run Ansible playbook inside the container
                    sh "docker run --rm -v \${PWD}/$REPO_FOLDER:/ansible ${ANSIBLE_IMAGE} ansible-playbook /ansible/playbook.yml"
                }
            }
        }
    }
}
