---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - name: Print Hello World
      ansible.builtin.debug:
        msg: 'Hello World from Ansible in Docker!'

    - name: Create a simple output file
      ansible.builtin.copy:
        content: 'Ansible container is working!'
        dest: /apps/output.txt
